name: Pull Request Workflow

on:
  pull_request:
    types:
      [opened, edited]
    branches:
      - main

jobs:

  build:
    name: Build
    needs: [ lint, test ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Generate AAR and APK files
        if: always()
        run: ./gradlew assembleDebug

      - name: Upload AAR files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/arr

  test:
    name: Run Unit Tests
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Unit Tests
        if: always()
        run: ./gradlew testDebugUnitTest

  lint:
    name: Lint
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CodeAnalysis via  detekt
        run: ./gradlew detekt

      - name: Upload detekt results
        uses: actions/upload-artifact@v2
        with:
          name: detekt_results
          path: app/build/reports/detekt




