name: Pull Request Workflow

on:
  pull_request:
    types:
      [opened, edited]
    branches:
      - main

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: CodeAnalysis via  detekt
        run: ./gradlew detekt

      - name: Upload detekt results
        uses: actions/upload-artifact@v2
        with:
          name: detekt_results
          path: app/build/reports/detekt

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Unit Tests
        if: always()
        run: ./gradlew testDebugUnitTest

  build_main:
    name: Build Main APK
    needs: [ test, lint ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Generate AAR and APK files
        if: always()
        run: ./gradlew assembleDebug

      - name: Upload AAR files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: |
            app/build/outputs/apk/debug/apk-master.apk
            app/build/outputs/arr

  build_pr:
    name: Build PR
    needs: [ test, lint ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate AAR and APK files
        if: always()
        run: ./gradlew assembleDebug

      - name: Upload AAR files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: |
            app/build/outputs/apk/debug/apk-pr.apk
            app/build/outputs/arr

  apk_difference:
    name: APK Difference
    needs: [ build_main, build_pr ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v1

      - name: Download APKs
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Execute Diffuse
        run: ./diffuse diff apk/apk-master.apk apk/apk-pr.apk

      - name: Upload Apk Diff Results
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: apk_differences
          path: apk_differences_summary.txt