name: Pull Request Workflow

on:
  pull_request:
    types:
      [opened, edited]
    branches:
      - main

jobs:

#  lint:
#    name: Lint
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: CodeAnalysis via  detekt
#        run: ./gradlew detekt
#
#      - name: Upload detekt results
#        uses: actions/upload-artifact@v2
#        with:
#          name: detekt_results
#          path: app/build/reports/detekt
#
#  test:
#    name: Run Unit Tests
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Run Unit Tests
#        if: always()
#        run: ./gradlew testDebugUnitTest

  build:
    name: Build
#    needs: [ test, lint ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate AAR and APK files
        if: always()
        run: ./gradlew assembleDebug

      - name: Upload AAR files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/arr

  apk_difference:
    name: APK Difference
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Download Previous Debug APK
          uses: dawidd6/action-download-artifact@v2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            workflow: main.yml
            name: artifacts

        - name: Run Apk Diff
          run: |
            gh release download -p '*.jar' -R jakewharton/diffuse 0.1.0
            java -jar diffuse-0.1.0-binary.jar diff app-debug.apk app/build/outputs/apk/debug/app-debug.apk > apk_differences.txt
            { echo "\`\`\`"; head -n 17 apk_differences.txt; echo "\`\`\`"; echo; } >> apk_differences_summary.txt
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Upload Apk Diff Results
          uses: actions/upload-artifact@v3
          if: success()
          with:
            name: apk_differences
            path: apk_differences_summary.txt